name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Disarm alert alarm
        run: |
          curl -s https://api.val.town/eval/@u.refresher\(\"prismarine-archive\"\)
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.GITLAB_PRIV_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.com > ~/.ssh/known_hosts
          ssh-keyscan -H codeberg.org >> ~/.ssh/known_hosts
          git config --global user.email "prismarine-archive@u9g.dev"
          git config --global user.name "prismarine-archive"
      - name: Run commands
        run: |
          pip install git+https://github.com/U9G/python-github-backup.git#egg=github-backup
          git clone git@gitlab.com:PrismarineJS/prismarine-archive.git
          cd prismarine-archive
          echo "renaming .git1 folders to .git"
          find . -type d -name "*.git1" -print0 | while IFS= read -r -d '' dir; do
              mv "$dir" "${dir%.git1}.git"
          done

          echo "running github-backup"
          github-backup -t "$GH_API_KEY" --as-app -o . --pull-details --gists --starred-gists -i --all PrismarineJS

          echo "renaming .git folders to .git1"
          find . -type d -name "*.git" -print0 | while IFS= read -r -d '' dir; do
              mv "$dir" "${dir%.git}.git1"
          done

          echo "moving the main .git back from .git1"
          mv .git1 .git

          echo "running git add ."
          git add .

          echo "running git commit"
          git commit -m "Update at $(date)" || echo "nothing new"

          echo "running git push"
          git push

          echo "adding codeberg remote and pushing"
          git remote add codeberg git@codeberg.org:PrismarineJS/prismarine-archive.git
          git push -u codeberg main
        env: # Or as an environment variable
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
